name: Run Gradle Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: ~
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Set up Gradle Build Action
      uses: gradle/gradle-build-action@v2
      with:
        # Removing unused files from Gradle User Home before saving to cache (i.e. older versions of gradle)
        gradle-home-cache-cleanup: true
        # Cache downloaded JDKs in addition to the default directories.
        gradle-home-cache-includes: |
          caches
          notifications
          jdks
            
    - name: Build with Gradle
      run: ./gradlew build --scan
